# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Daily get UP-FRONT & Hello!Project YouTube view count

env:
  ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
  ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
  API_KEY: ${{secrets.API_KEY}}
  API_SECRET: ${{secrets.API_SECRET}}
  YTV3_API_KEY: ${{secrets.YTV3_API_KEY}}
  DEBUG: NO
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FIREBASE_CREDENTIAL: ${{ secrets.FIREBASE_CREDENTIAL }}
  TZ: 'Asia/Tokyo'



on:
  schedule:
    - cron: '0 23 * * *'

# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
jobs:
  job:
    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Chromium
        run: sudo apt install chromium-browser
        
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
          pip freeze
          rm -rf images/*
          rm -rf html/*          
        
        
      - name: get today data
        id: main.async.py
        run: |
          python main.async.py 2>&1 | tee ./out.txt
        continue-on-error: true

      - name: push updates
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git status; \
            git add save.sqlite save.xlsx images/* html/* tsvs/*; \
            git commit -m "Daily updates"; \
            git push origin HEAD:${GITHUB_REF} -f ; \
          fi


      - name: Print status
        run:  echo "${{steps.auto-run.outcome}}"
        
      - name: Error Handling
        if: steps.auto-run.outcome == 'failure'
        run: |
          pipenv run post-processing
          exit 1

      - name: Upload Log
        if: steps.auto-run.outcome != 'failure'
        run: |
          pipenv run upload-log
      
        
