# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: TEST get UP-FRONT & Hello!Project YouTube view count

env:
  ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
  ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
  API_KEY: ${{secrets.API_KEY}}
  API_SECRET: ${{secrets.API_SECRET}}
  YTV3_API_KEY: ${{secrets.YTV3_API_KEY}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEBUG: True
permissions: 
  contents: read
  issues: write

on:
  push:
    branches: [ test ]

jobs:
  build:
    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: get today data
      - id: auto-run
        run: |
          pipenv run auto-run > ./out.txt
        continue-on-error: true
      - name: generate log
      - run: |
          result="$(cat ./out.txt)"
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          echo "result=${result}" >> $GITHUB_ENV

        
      - name: Error Handling
        uses: JasonEtco/create-an-issue@v2
        if: steps.auto-run.outcome == 'failure'
        env: 
          GITHUB_TOKEN: ${{ github.token }}
          result: ${{ env.result }}
        
