# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: TEST get UP-FRONT & Hello!Project YouTube view count

env:
  ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
  ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
  API_KEY: ${{secrets.API_KEY}}
  API_SECRET: ${{secrets.API_SECRET}}
  YTV3_API_KEY: ${{secrets.YTV3_API_KEY}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEBUG: True
permissions:
  contents: read
  issues: write

on:
  push:
    branches: [ test ]

jobs:
  job:
    timeout-minutes: 15

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
      - id: auto-run
        name: get today data
        run: |
          exit 1
          pipenv run auto-run 2>&1 | tee ./out.txt
        continue-on-error: true

      - name: set time to env
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: generate log
        run: |
          echo "pass"
        # python post-processing.py
        #          result="$(cat ./out.txt)"
        #          result="${result//'%'/'%25'}"
        #          result="${result//$'\n'/'%0A'}"
        #          result="${result//$'\r'/'%0D'}"
        #          echo "result=${result}" >> $GITHUB_ENV


      - name: Error Handling
        if: steps.auto-run.outcome == 'failure'
        run: |
          python post-processing.py
          exit 1